In [8]:
import fsspec
import xarray as xr
from kerchunk import combine, hdf

In [9]:
dir(hdf)

['BinaryIO',
 'FillStringsCodec',
 'SingleHdf5ToZarr',
 'Union',
 '_HIDDEN_ATTRS',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_encode_for_JSON',
 '_is_netcdf_datetime',
 '_is_netcdf_variable',
 '_read_block',
 '_simple_type',
 'base64',
 'encode_fill_value',
 'fsspec',
 'h5py',
 'lggr',
 'logging',
 'np',
 'numcodecs',
 'zarr']

In [10]:
def get_refs(nfile):
    return hdf.SingleHdf5ToZarr(nfile).translate()

def combine_refs(refset,**kwargs):
    return combine.MultiZarrToZarr(refset, concat_dims=['time'], **kwargs).translate()

In [11]:
ukcp_fileset = """/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_19801201-19901130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_19901201-20001130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20001201-20101130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20101201-20201130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20201201-20301130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20301201-20401130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20401201-20501130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20501201-20601130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20601201-20701130.nc
/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20701201-20801130.nc""".split('\n')
ukcp_fileset

['/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_19801201-19901130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_19901201-20001130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20001201-20101130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20101201-20201130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20201201-20301130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20301201-20401130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20401201-20501130.nc',
 '/badc/ukcp18/data/land-rcm/uk/12km/rcp85/01/clt/day/v20190731/clt_rcp85_land-rcm_uk_12km_01_day_20501201-20601130.nc',
 '/badc/ukcp18/data/land-rcm/uk/

In [12]:
ref1 = get_refs(ukcp_fileset[0])

In [13]:
ref2 = get_refs(ukcp_fileset[1])

In [88]:
mzz = combine_refs([ref1,ref2], identical_dims=['ensemble_member_id', 'grid_latitude','grid_longitude'])

In [103]:
ds = xr.open_zarr(fsspec.get_mapper('reference://',fo=mzz2),consolidated=False)

In [104]:
ds.ensemble_member_id.shape, ds.ensemble_member.shape

((1,), (1,))

In [66]:
ref1['refs']['ensemble_member_id/.zattrs']

'{"_ARRAY_DIMENSIONS":["ensemble_member","string27"],"long_name":"ensemble_member_id","units":"1"}'

In [83]:
import json
for var in list(xarr_1.variables):
    attrs = json.loads(ref1['refs'][f'{var}/.zattrs'])
    print(var, attrs['_ARRAY_DIMENSIONS'])

clt ['ensemble_member', 'time', 'projection_y_coordinate', 'projection_x_coordinate']
transverse_mercator []
ensemble_member ['ensemble_member']
time ['time']
time_bnds ['time', 'bnds']
projection_y_coordinate ['projection_y_coordinate']
projection_y_coordinate_bnds ['projection_y_coordinate', 'bnds']
projection_x_coordinate ['projection_x_coordinate']
projection_x_coordinate_bnds ['projection_x_coordinate', 'bnds']
ensemble_member_id ['ensemble_member', 'string27']
grid_latitude ['projection_y_coordinate', 'projection_x_coordinate']
grid_longitude ['projection_y_coordinate', 'projection_x_coordinate']
month_number ['time']
year ['time']
yyyymmdd ['time', 'string64']


In [ ]:
mzz['refs']['grid_latitude/.zattrs']

In [108]:
xarr_1 = xr.open_mfdataset(ukcp_fileset[:2])
xarr_2 = xr.concat([xr.open_dataset(ukcp_fileset[0]), xr.open_dataset(ukcp_fileset[1])], dim='time', data_vars='minimal')

In [109]:
for var in list(xarr_1.variables):
    print(var, xarr_2[var].shape, ds[var].shape)

clt (1, 7200, 112, 82) (1, 7200, 112, 82)
transverse_mercator () ()
ensemble_member (1,) (1,)
time (7200,) (7200,)
time_bnds (7200, 2) (7200, 2)
projection_y_coordinate (112,) (112,)
projection_y_coordinate_bnds (112, 2) (112, 2)
projection_x_coordinate (82,) (82,)
projection_x_coordinate_bnds (82, 2) (82, 2)
ensemble_member_id (1,) (1,)
grid_latitude (112, 82) (112, 82)
grid_longitude (112, 82) (112, 82)
month_number (7200,) (7200,)
year (7200,) (7200,)
yyyymmdd (7200,) (7200,)


In [76]:
xarr_1.grid_latitude.shape

(112, 82)

In [74]:
ds.grid_latitude.shape

(7200, 112, 82)

In [14]:
from pipeline.validate import validate_data
from pipeline.logs import init_logger
testlog = init_logger(1,0,'test')

In [15]:
from pipeline.errors import ShapeMismatchError
import xarray as xr
import fsspec
ds1 = xr.open_zarr(fsspec.get_mapper('reference://',fo=ref1),consolidated=False)
ds2 = xr.open_zarr(fsspec.get_mapper('reference://',fo=ref2),consolidated=False)
identicals = []
for var in ds1.variables:
    if 'time' not in ds1[var].dims:
        try:
            validate_data(ds1, ds2, var, 0, testlog, bypass=True)
            print('Duplicate: ',var)
            identicals.append(var)
        except ShapeMismatchError:
            # Non duplicate
            print('Non-duplicate: ',var)
    else:
        print('Time-dependent: ',var)
mzz2 = combine_refs([ref1,ref2], identical_dims=identicals)

INFO [test]: ensemble_member : Starting growbox data tests for 0
INFO [test]: ensemble_member : Starting growbox data tests for 0
INFO [test]: ensemble_member_id : Starting growbox data tests for 0
INFO [test]: ensemble_member_id : Starting growbox data tests for 0


Time-dependent:  clt
Duplicate:  ensemble_member


WARNING [test]: Max comparison skipped for non-summable values in ensemble_member_id
WARNING [test]: Max comparison skipped for non-summable values in ensemble_member_id
WARNING [test]: Min comparison skipped for non-summable values in ensemble_member_id
WARNING [test]: Min comparison skipped for non-summable values in ensemble_member_id
WARNING [test]: Mean comparison skipped for non-summable values in ensemble_member_id
WARNING [test]: Mean comparison skipped for non-summable values in ensemble_member_id
INFO [test]: grid_latitude : Starting growbox data tests for 0
INFO [test]: grid_latitude : Starting growbox data tests for 0
INFO [test]: grid_longitude : Starting growbox data tests for 0
INFO [test]: grid_longitude : Starting growbox data tests for 0
INFO [test]: projection_x_coordinate : Starting growbox data tests for 0
INFO [test]: projection_x_coordinate : Starting growbox data tests for 0
INFO [test]: projection_x_coordinate_bnds : Starting growbox data tests for 0
INFO [test

Duplicate:  ensemble_member_id
Duplicate:  grid_latitude
Duplicate:  grid_longitude
Time-dependent:  month_number
Duplicate:  projection_x_coordinate
Duplicate:  projection_x_coordinate_bnds
Duplicate:  projection_y_coordinate
Duplicate:  projection_y_coordinate_bnds
Time-dependent:  time
Time-dependent:  time_bnds
nan
Duplicate:  transverse_mercator
Time-dependent:  year
Time-dependent:  yyyymmdd


<xarray.DataArray 'transverse_mercator' (time: 7200)>
array([-2147483647, -2147483647, -2147483647, ..., -2147483647,
       -2147483647, -2147483647], dtype=int32)
Coordinates:
  * time          (time) object 1980-12-01 12:00:00 ... 2000-11-30 12:00:00
    month_number  (time) int32 dask.array<chunksize=(3600,), meta=np.ndarray>
    year          (time) int32 dask.array<chunksize=(3600,), meta=np.ndarray>
    yyyymmdd      (time) |S64 dask.array<chunksize=(3600,), meta=np.ndarray>
Attributes:
    grid_mapping_name:                 transverse_mercator
    longitude_of_prime_meridian:       0.0
    semi_major_axis:                   6377563.396
    semi_minor_axis:                   6356256.909
    longitude_of_central_meridian:     -2.0
    latitude_of_projection_origin:     49.0
    false_easting:                     400000.0
    false_northing:                    -100000.0
    scale_factor_at_central_meridian:  0.9996012717

In [120]:
class Args:
    def __init__(self):
        self.bypass = True

In [16]:
allfile = "/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/in_progress/CMIP6_rel1_6233/CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_uas_gn_v20200511/allfiles.txt"
with open(allfile) as f:
    fileset = [r.strip() for r in f.readlines()]

In [17]:
import xarray as xr
ds_set = []
for f in fileset:
    ds_set.append(xr.open_dataset(f))
ds = xr.concat(ds_set, dim='time',data_vars='minimal')

In [18]:
ds.lon_bnds.shape

(384, 2)

In [1]:
kfile1 = "/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/in_progress/CMIP6_rel1_6233/CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_uas_gn_v20200511/cache/0.json"
kfile2 = kfile1.replace("0.json", "1.json")

In [18]:
from pipeline.validate import open_kerchunk
from pipeline.logs import FalseLogger
import fsspec
import xarray as xr

kfile1 = "/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/in_progress/CMIP6_rel1_6233/CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_uas_gn_v20200511/kerchunk-1a.json"

kf1 = open_kerchunk(kfile1, FalseLogger())
mapper = fsspec.get_mapper('reference://',fo=kfile1, remote_protocol='https')
kf2 = xr.open_zarr(mapper, consolidated=False)

In [20]:
kf2.time.sel(time='1850-01-16')

<xarray.DataArray 'time' (time: 1)>
array(['1850-01-16T12:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
    height   float64 ...
  * time     (time) datetime64[ns] 1850-01-16T12:00:00
Attributes:
    axis:           T
    bounds:         time_bnds
    long_name:      time
    standard_name:  time

In [11]:
kf2.lon_bnds.compute()

<xarray.DataArray 'lon_bnds' (lon: 384, bnds: 2)>
array([[ -0.46875,   0.46875],
       [  0.46875,   1.40625],
       [  1.40625,   2.34375],
       [  2.34375,   3.28125],
       [  3.28125,   4.21875],
       [  4.21875,   5.15625],
       [  5.15625,   6.09375],
       [  6.09375,   7.03125],
       [  7.03125,   7.96875],
       [  7.96875,   8.90625],
       [  8.90625,   9.84375],
       [  9.84375,  10.78125],
       [ 10.78125,  11.71875],
       [ 11.71875,  12.65625],
       [ 12.65625,  13.59375],
       [ 13.59375,  14.53125],
       [ 14.53125,  15.46875],
       [ 15.46875,  16.40625],
       [ 16.40625,  17.34375],
       [ 17.34375,  18.28125],
...
       [340.78125, 341.71875],
       [341.71875, 342.65625],
       [342.65625, 343.59375],
       [343.59375, 344.53125],
       [344.53125, 345.46875],
       [345.46875, 346.40625],
       [346.40625, 347.34375],
       [347.34375, 348.28125],
       [348.28125, 349.21875],
       [349.21875, 350.15625],
       [350.15625, 351.09375],
       [351.09375, 352.03125],
       [352.03125, 352.96875],
       [352.96875, 353.90625],
       [353.90625, 354.84375],
       [354.84375, 355.78125],
       [355.78125, 356.71875],
       [356.71875, 357.65625],
       [357.65625, 358.59375],
       [358.59375, 359.53125]])
Coordinates:
    height   float64 10.0
  * lon      (lon) float64 6.946e-310 6.946e-310 ... 2.451e+198 4.572e+228
Dimensions without coordinates: bnds

In [13]:
import numpy as np
kf1 = np.array(kf1.lon_bnds)
kf2 = np.array(kf2.lon_bnds)

In [16]:
np.array_equal(kf1, kf2)

True

In [46]:
import os
ingest_file = '/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/groups/CMIP6_rel1_6233/proj_codes_complete_ingest.txt'
in_place = '/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/complete/CMIP6_rel1_6233'
with open(ingest_file) as f:
    datasets = [f'{in_place}/{r.strip()}_kr1.0.json' for r in f.readlines()]

for d in datasets[3:8]:
    os.system(f'cp {d} {d.replace("CMIP6_rel1_6233","sample")}')

In [ ]:
for x, d in enumerate(datasets):
    with open(d) as f:
        print(x, len(f.readlines()))

In [29]:
path = '/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/in_progress/CMIP6_rel1_6233'
kfile0 = f'{path}/CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_huss_gn_v20201013/cache/0.json'
kfile0a = f'{path}/CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_huss_gn_v20201013/cache/0a.json'
kfile1 = f'{path}/CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_huss_gn_v20201013/cache/1.json'
print(kfile0)

/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/in_progress/CMIP6_rel1_6233/CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_huss_gn_v20201013/cache/0.json


In [33]:
import fsspec
import xarray as xr

mapper = fsspec.get_mapper('reference://',fo=kfile0, remote_protocol='https')
kf = xr.open_zarr(mapper, consolidated=False)
kf.lata

<xarray.DataArray 'lat' (lat: 192)>
array([6.918039e-310, 4.656565e-310, 0.000000e+000, 0.000000e+000,
       6.013470e-154, 0.000000e+000, 6.013470e-154, 2.318609e-052,
       6.031042e-154, 2.318609e-052, 6.031042e-154, 1.398043e-076,
       6.031042e-154, 1.398043e-076, 2.440053e-154, 5.516754e-048,
       2.628400e+179, 3.615501e-043, 2.624599e+179, 2.990673e-067,
       3.113418e+179, 1.284484e-057, 3.920697e+179, 5.981491e-154,
       3.845686e-086, 5.205553e-090, 4.247839e-086, 5.205557e-090,
       3.443533e-086, 5.207482e-090, 3.845686e-086, 5.200759e-090,
       6.013345e-154, 1.303543e-076, 1.182951e-076, 1.303543e-076,
       1.182951e-076, 1.303712e-076, 3.572812e-062, 1.577110e-052,
       1.269312e-076, 6.013470e-154, 4.079204e-033, 1.174786e-047,
       1.028977e-071, 1.688992e-052, 3.308835e-033, 1.688992e-052,
       1.084292e-042, 1.174786e-047, 6.013470e-154, 1.398041e-076,
       2.421365e-052, 1.723981e-047, 1.518178e-047, 1.656093e-047,
       6.750722e-067, 1.520050e-047, 1.030078e-071, 6.013470e-154,
       1.398043e-076, 7.578808e-096, 1.398043e-076, 7.578808e-096,
       1.398043e-076, 7.578808e-096, 2.318609e-052, 7.580658e-096,
       6.013470e-154, 5.157233e-062, 1.051480e-153, 1.588475e-047,
       1.051188e-153, 3.942742e-062, 1.051188e-153, 3.942742e-062,
       1.145834e-259, 6.013470e-154, 8.604357e-043, 6.031042e-154,
       1.398043e-076, 6.031042e-154, 2.318609e-052, 6.031042e-154,
       1.398043e-076, 2.440053e-154, 2.990638e-067, 3.602222e+179,
       6.963202e-077, 2.623958e+179, 1.552846e-033, 3.597770e+179,
       5.516817e-048, 3.436948e+179, 5.981491e-154, 3.845686e-086,
       5.203662e-090, 4.448916e-086, 5.206504e-090, 4.448916e-086,
       5.209399e-090, 4.448916e-086, 5.209399e-090, 6.013345e-154,
       2.909255e-033, 3.572813e-062, 2.909255e-033, 3.572813e-062,
       2.909255e-033, 3.572813e-062, 2.909255e-033, 3.572813e-062,
       6.013470e-154, 1.425167e-071, 1.085398e-071, 1.425167e-071,
       1.085398e-071, 1.425167e-071, 1.085398e-071, 1.425167e-071,
       1.085398e-071, 6.013470e-154, 7.723222e-043, 1.485413e-076,
       7.723222e-043, 1.485413e-076, 7.723222e-043, 1.485413e-076,
       7.723222e-043, 1.485413e-076, 6.013470e-154, 1.039978e-042,
       7.580658e-096, 1.039978e-042, 7.580658e-096, 1.039978e-042,
       7.580658e-096, 1.039978e-042, 7.580658e-096, 6.013470e-154,
       2.423821e-052, 1.051188e-153, 2.423821e-052, 1.051188e-153,
       2.423821e-052, 1.051188e-153, 2.423821e-052, 1.145834e-259,
       6.013470e-154, 4.085992e-033, 6.031042e-154, 4.085992e-033,
       6.031042e-154, 4.085992e-033, 6.031042e-154, 4.085992e-033,
       2.440053e-154, 5.516754e-048, 4.085956e+179, 5.516817e-048,
       4.085956e+179, 6.963202e-077, 2.623958e+179, 6.963202e-077,
       2.623958e+179, 5.981491e-154, 3.242457e-086, 1.210894e-099,
       3.242457e-086, 1.210894e-099, 3.242457e-086, 1.210894e-099,
       3.242457e-086, 1.210894e-099, 6.013345e-154, 1.303543e-076,
       1.182951e-076, 1.303543e-076, 1.182951e-076, 1.303543e-076,
       1.182951e-076, 1.303543e-076, 1.182951e-076, 6.013470e-154,
       1.397369e-076, 1.396426e-076, 1.397369e-076, 1.396426e-076,
       1.425167e-071, 1.085398e-071, 1.425167e-071, 1.085398e-071])
Coordinates:
    height   float64 ...
  * lat      (lat) float64 6.918e-310 4.657e-310 0.0 ... 1.425e-71 1.085e-71
Attributes:
    axis:           Y
    bounds:         lat_bnds
    long_name:      Latitude
    standard_name:  latitude
    units:          degrees_north

In [41]:
import fsspec
import xarray as xr

mapper = fsspec.get_mapper('reference://',fo=kfile0a, remote_protocol='file')
kfa = xr.open_zarr(mapper, consolidated=False)
kfa.lat

<xarray.DataArray 'lat' (lat: 192)>
array([-90.      , -89.057592, -88.115183, -87.172775, -86.230366, -85.287958,
       -84.34555 , -83.403141, -82.460733, -81.518325, -80.575916, -79.633508,
       -78.691099, -77.748691, -76.806283, -75.863874, -74.921466, -73.979058,
       -73.036649, -72.094241, -71.151832, -70.209424, -69.267016, -68.324607,
       -67.382199, -66.439791, -65.497382, -64.554974, -63.612565, -62.670157,
       -61.727749, -60.78534 , -59.842932, -58.900524, -57.958115, -57.015707,
       -56.073298, -55.13089 , -54.188482, -53.246073, -52.303665, -51.361257,
       -50.418848, -49.47644 , -48.534031, -47.591623, -46.649215, -45.706806,
       -44.764398, -43.82199 , -42.879581, -41.937173, -40.994764, -40.052356,
       -39.109948, -38.167539, -37.225131, -36.282723, -35.340314, -34.397906,
       -33.455497, -32.513089, -31.570681, -30.628272, -29.685864, -28.743455,
       -27.801047, -26.858639, -25.91623 , -24.973822, -24.031414, -23.089005,
       -22.146597, -21.204188, -20.26178 , -19.319372, -18.376963, -17.434555,
       -16.492147, -15.549738, -14.60733 , -13.664921, -12.722513, -11.780105,
       -10.837696,  -9.895288,  -8.95288 ,  -8.010471,  -7.068063,  -6.125654,
        -5.183246,  -4.240838,  -3.298429,  -2.356021,  -1.413613,  -0.471204,
         0.471204,   1.413613,   2.356021,   3.298429,   4.240838,   5.183246,
         6.125654,   7.068063,   8.010471,   8.95288 ,   9.895288,  10.837696,
        11.780105,  12.722513,  13.664921,  14.60733 ,  15.549738,  16.492147,
        17.434555,  18.376963,  19.319372,  20.26178 ,  21.204188,  22.146597,
        23.089005,  24.031414,  24.973822,  25.91623 ,  26.858639,  27.801047,
        28.743455,  29.685864,  30.628272,  31.570681,  32.513089,  33.455497,
        34.397906,  35.340314,  36.282723,  37.225131,  38.167539,  39.109948,
        40.052356,  40.994764,  41.937173,  42.879581,  43.82199 ,  44.764398,
        45.706806,  46.649215,  47.591623,  48.534031,  49.47644 ,  50.418848,
        51.361257,  52.303665,  53.246073,  54.188482,  55.13089 ,  56.073298,
        57.015707,  57.958115,  58.900524,  59.842932,  60.78534 ,  61.727749,
        62.670157,  63.612565,  64.554974,  65.497382,  66.439791,  67.382199,
        68.324607,  69.267016,  70.209424,  71.151832,  72.094241,  73.036649,
        73.979058,  74.921466,  75.863874,  76.806283,  77.748691,  78.691099,
        79.633508,  80.575916,  81.518325,  82.460733,  83.403141,  84.34555 ,
        85.287958,  86.230366,  87.172775,  88.115183,  89.057592,  90.      ])
Coordinates:
    height   float64 ...
  * lat      (lat) float64 -90.0 -89.06 -88.12 -87.17 ... 87.17 88.12 89.06 90.0
Attributes:
    axis:           Y
    bounds:         lat_bnds
    long_name:      Latitude
    standard_name:  latitude
    units:          degrees_north

In [5]:
ncf1 = '/badc/cmip6/data/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/3hr/huss/gn/v20201013/huss_3hr_TaiESM1_historical_r1i1p1f1_gn_185001010000-185912312230.nc'
ds = xr.open_dataset('/badc/cmip6/data/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/3hr/huss/gn/v20201013/huss_3hr_TaiESM1_historical_r1i1p1f1_gn_185001010000-185912312230.nc')

In [35]:
from kerchunk.hdf import SingleHdf5ToZarr
import json
ncf1 = '/badc/cmip6/data/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/3hr/huss/gn/v20201013/huss_3hr_TaiESM1_historical_r1i1p1f1_gn_185001010000-185912312230.nc'
refs = SingleHdf5ToZarr(ncf1, inline_threshold=1000).translate()
ds = xr.open_zarr(fsspec.get_mapper('reference://',fo=refs), consolidated=False)

In [37]:
ds.lat

<xarray.DataArray 'lat' (lat: 192)>
array([-90.      , -89.057592, -88.115183, -87.172775, -86.230366, -85.287958,
       -84.34555 , -83.403141, -82.460733, -81.518325, -80.575916, -79.633508,
       -78.691099, -77.748691, -76.806283, -75.863874, -74.921466, -73.979058,
       -73.036649, -72.094241, -71.151832, -70.209424, -69.267016, -68.324607,
       -67.382199, -66.439791, -65.497382, -64.554974, -63.612565, -62.670157,
       -61.727749, -60.78534 , -59.842932, -58.900524, -57.958115, -57.015707,
       -56.073298, -55.13089 , -54.188482, -53.246073, -52.303665, -51.361257,
       -50.418848, -49.47644 , -48.534031, -47.591623, -46.649215, -45.706806,
       -44.764398, -43.82199 , -42.879581, -41.937173, -40.994764, -40.052356,
       -39.109948, -38.167539, -37.225131, -36.282723, -35.340314, -34.397906,
       -33.455497, -32.513089, -31.570681, -30.628272, -29.685864, -28.743455,
       -27.801047, -26.858639, -25.91623 , -24.973822, -24.031414, -23.089005,
       -22.146597, -21.204188, -20.26178 , -19.319372, -18.376963, -17.434555,
       -16.492147, -15.549738, -14.60733 , -13.664921, -12.722513, -11.780105,
       -10.837696,  -9.895288,  -8.95288 ,  -8.010471,  -7.068063,  -6.125654,
        -5.183246,  -4.240838,  -3.298429,  -2.356021,  -1.413613,  -0.471204,
         0.471204,   1.413613,   2.356021,   3.298429,   4.240838,   5.183246,
         6.125654,   7.068063,   8.010471,   8.95288 ,   9.895288,  10.837696,
        11.780105,  12.722513,  13.664921,  14.60733 ,  15.549738,  16.492147,
        17.434555,  18.376963,  19.319372,  20.26178 ,  21.204188,  22.146597,
        23.089005,  24.031414,  24.973822,  25.91623 ,  26.858639,  27.801047,
        28.743455,  29.685864,  30.628272,  31.570681,  32.513089,  33.455497,
        34.397906,  35.340314,  36.282723,  37.225131,  38.167539,  39.109948,
        40.052356,  40.994764,  41.937173,  42.879581,  43.82199 ,  44.764398,
        45.706806,  46.649215,  47.591623,  48.534031,  49.47644 ,  50.418848,
        51.361257,  52.303665,  53.246073,  54.188482,  55.13089 ,  56.073298,
        57.015707,  57.958115,  58.900524,  59.842932,  60.78534 ,  61.727749,
        62.670157,  63.612565,  64.554974,  65.497382,  66.439791,  67.382199,
        68.324607,  69.267016,  70.209424,  71.151832,  72.094241,  73.036649,
        73.979058,  74.921466,  75.863874,  76.806283,  77.748691,  78.691099,
        79.633508,  80.575916,  81.518325,  82.460733,  83.403141,  84.34555 ,
        85.287958,  86.230366,  87.172775,  88.115183,  89.057592,  90.      ])
Coordinates:
    height   float64 ...
  * lat      (lat) float64 -90.0 -89.06 -88.12 -87.17 ... 87.17 88.12 89.06 90.0
Attributes:
    axis:           Y
    bounds:         lat_bnds
    long_name:      Latitude
    standard_name:  latitude
    units:          degrees_north

In [38]:
import json
import os
os.system(f'rm {kfile0a}')
with open(kfile0a,'w') as f:
    f.write(json.dumps(refs))

In [28]:
refs['refs']['lat/0']

['/badc/cmip6/data/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/3hr/huss/gn/v20201013/huss_3hr_TaiESM1_historical_r1i1p1f1_gn_185001010000-185912312230.nc',
 41084,
 1536]

In [16]:
import glob
complete = '/gws/nopw/j04/cmip6_prep_vol1/kerchunk-pipeline/complete/CMIP6_rel1_6233/*.json'

paths = glob.glob(complete)
for p in paths:
    allfiles = p.replace('complete','in_progress').replace('_kr1.0.json','/allfiles.txt')
    with open(allfiles) as f:
        if len(f.readlines()) > 1:
            print(p[73:-11])

CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_clt_gn_v20201013
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_rlus_gn_v20201013
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_3hr_rsds_gn_v20201013
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_clt_gn_v20200626
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_pr_gn_v20200626
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_psl_gn_v20200626
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_rlds_gn_v20200626
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_rlus_gn_v20200626
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_rsds_gn_v20200626
CMIP_AS-RCEC_TaiESM1_historical_r1i1p1f1_day_rsus_gn_v20200626
CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_3hr_rlus_gn_v20181218
CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_clt_gn_v20200511
CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_pr_gn_v20200511
CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_prsn_gn_v20200511
CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_psl_gn_v20181218
CMIP_AWI_AWI-CM-1-1-MR_historical_r1i1p1f1_Amon_rl